pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  buildProjectFunctions: '**/FunctionsAppV3.csproj'
  deployToAzure: $(DEPLOY_TO_AZURE)
  tag: '1.0.0'
  buildNumber: $(Build.BuildNumber)

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: |
      $(buildProjectFunctions)
    arguments: '--configuration $(BuildConfiguration) /p:Version=1.0.0-$(buildNumber)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
  inputs:
    command: publish
    projects: |
      $(buildProjectFunctions)
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) /p:Version=1.0.0-$(BuildNumber) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#file-structure-for-output-files-is-different-from-previous-builds
    modifyOutputPath: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests

- task: AzureAppServiceManage@0
  condition: and(succeeded(), eq(variables.deployToAzure, 'yes'), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
  displayName: Stop
  inputs:
    azureSubscription: 'Service Connection Azure Functions V3'
    Action: 'Stop Azure App Service'
    WebAppName: 'stef-function-app-linux-v3'

- task: AzureRmWebAppDeployment@4
  condition: and(succeeded(), eq(variables.deployToAzure, 'yes'), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
  displayName: Deploy
  inputs:
    azureSubscription: 'Service Connection Azure Functions V3'
    appType: functionAppLinux
    WebAppName: 'stef-function-app-linux-v3'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
    RuntimeStackFunction: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'  

- task: AzureAppServiceManage@0
  condition: and(succeeded(), eq(variables.deployToAzure, 'yes'), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
  displayName: Start
  inputs:
    azureSubscription: 'Service Connection Azure Functions V3'
    Action: 'Start Azure App Service'
    WebAppName: 'stef-function-app-linux-v3'