pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  buildProjectFunctions: '**/FunctionsAppV3.csproj'
  publishToAzure: $(PUBLISH_TO_AZURE)
  tag: '1.0.0'
  buildNumber: $(Build.BuildNumber)

steps:
- task: DotNetCoreCLI@2
  displayName: 'Function : Build'
  inputs:
    command: build
    projects: |
      $(buildProjectFunctions)
    arguments: '--configuration $(BuildConfiguration) /p:Version=1.0.0-$(buildNumber)'

- task: DotNetCoreCLI@2
  displayName: 'Function : Publish'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
  inputs:
    command: publish
    projects: |
      $(buildProjectFunctions)
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) /p:Version=1.0.0-$(BuildNumber) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#file-structure-for-output-files-is-different-from-previous-builds
    modifyOutputPath: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy'
  inputs:
    azureSubscription: 'Service Connection Azure Functions V3'
    appType: functionAppLinux
    appName: 'stef-function-apps-linux-v3'
    #package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    runtimeStack: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'
  condition: and(succeeded(), eq(variables.publishToAzure, 'yes'))